---
on:
  push:
    branches:
      - main

jobs:
  release:
    uses: "Mosher-Labs/.github/.github/workflows/release.yml@main"
    permissions:
      contents: write
      issues: write
      pull-requests: write

  heimdallr:
    needs: release
    uses: "Mosher-Labs/.github/.github/workflows/heimdallr.yml@main"
    permissions:
      contents: write
      issues: write
      pull-requests: write
    secrets: inherit
    with:
      slack_message: "The project <https://github.com/${{ github.repository }}|${{ github.repository }}> just released version <https://github.com/${{ github.repository }}/releases/tag/${{ needs.release.outputs.next_version }}|${{ needs.release.outputs.next_version }}>."
