---
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  release:
    uses: "Mosher-Labs/.github/.github/workflows/release.yml@fix-full-checkout-prs"
    permissions:
      contents: write
      issues: write
      pull-requests: write
    with:
      enable_draft: ${{ github.ref_name != 'main' }}

  heimdallr:
    needs: release
    uses: "Mosher-Labs/.github/.github/workflows/heimdallr.yml@main"
    permissions:
      contents: write
      issues: write
      pull-requests: write
    secrets: inherit
    with:
      slack_message: "The project <https://github.com/${{ github.repository }}|${{ github.repository }}> just released version <https://github.com/${{ github.repository }}/releases/tag/${{ needs.release.outputs.next_version }}|${{ needs.release.outputs.next_version }}>."
      enable_comment_on_pr: ${{ github.ref_name != 'main' }}
